Controllers/OgretmenController.cs
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace efcoreApp.Controllers
{
    public class OgretmenController : Controller
    {
        private readonly DataContext _context;
        public OgretmenController(DataContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var ogretmen = await _context.Ogretmenler.ToListAsync();
            return View(ogretmen);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Ogretmen model)
        {
            _context.Ogretmenler.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ogr = await _context.Ogretmenler
            .Include(o => o.Kurslar)
            .FirstOrDefaultAsync(o => o.OgretmenId == id);
            //var ogr = await _context.Ogrenciler.FirstOrDefaultAsync(o=>o.Eposta=="id");
            if (ogr == null)
            {
                return NotFound();
            }
            return View(ogr);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Ogretmen model)
        {
            if (id != model.OgretmenId)
            {
                NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (System.Exception)
                {
                    {
                        throw;
                    }

                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ogretmen = await _context.Ogretmenler.FindAsync(id);
            if (ogretmen == null)
            {
                return NotFound();

            }
            return View(ogretmen);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromForm] int id)
        {
            var ogretmen = await _context.Ogretmenler.FindAsync(id);
            if (ogretmen == null)
            {
                return NotFound();
            }
            _context.Ogretmenler.Remove(ogretmen);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }


    }
}

Views/Ogretmen/Create.cshtml
@model Ogretmen
@{
ViewData["Title"] = "Öğretmen Kayıt";
}

<div class="form-group">
    <form asp-controller="Ogretmen" asp-action="Create" method="post">
        <div class="mb-3">
            <label asp-for="Ad" class="form-label">Öğretmen Adı</label>
            <input asp-for="Ad" class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="Soyad" class="form-label">Öğrenci Soyadı</label>
            <input asp-for="Soyad" class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="Eposta" class="form-label">Eposta Adresi</label>
            <input asp-for="Eposta" class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="Telefon" class="form-label">Telefon</label>
            <input asp-for="Telefon" class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="BaslamaTarihi" class="form-label">Başlama Tarihi</label>
            <input asp-for="BaslamaTarihi" class="form-control">
        </div>

        <button type="submit" class="btn btn-secondary">Ekle</button>
    </form>
</div>

Views/Ogretmen/Delete.cshtml
@model Ogretmen
@{
ViewData["Title"] = "Öğretmen Silme";
}
<p>
    <b>@Model.AdSoyad</b> isimli kaydı silmek istiyor musunuz?
</p>
<form asp-action="Delete" method="post">
    <input type="hidden" value="@Model.OgretmenId" name="id">
    <button type="submit" class="btn btn-danger">Evet</button>
    <a asp-action="Index" class="btn btn-primary">Hayır</a>
</form>

Views/Ogretmen/Edit.cshtml
@model Ogretmen
@{
ViewData["Title"] = "öğretmen Güncelleme";
}
<div class="row">
    <div class="col-8">
        <div class="form-group">
            <form asp-controller="Ogretmen" asp-action="Edit" method="post">
                <input type="hidden" asp-for="OgretmenId">
                <div class="mb-3">
                    <label asp-for="Ad" class="form-label">Öğretmen Adı</label>
                    <input asp-for="Ad" class="form-control">
                </div>
                <div class="mb-3">
                    <label asp-for="Soyad" class="form-label">Öğretmen Soyadı</label>
                    <input asp-for="Soyad" class="form-control">
                </div>
                <div class="mb-3">
                    <label asp-for="Eposta" class="form-label">Eposta Adresi</label>
                    <input asp-for="Eposta" class="form-control">
                </div>
                <div class="mb-3">
                    <label asp-for="Telefon" class="form-label">Telefon</label>
                    <input asp-for="Telefon" class="form-control">
                </div>
                <div class="mb-3">
                    <label asp-for="BaslamaTarihi" class="form-label">Başlama Tarihi</label>
                    <input asp-for="BaslamaTarihi" class="form-control">
                </div>
                <button type="submit" class="btn btn-secondary">Ekle</button>
            </form>
        </div>
    </div>
    <div class="col-4">
        <h4>Kurslar</h4>
        <hr>
        <ul>
            @foreach(var item in @Model.Kurslar)
            {
            <li>@item.Baslik</li>
            }
        </ul>
    </div>
</div>

Views/Ogretmen/Index.cshtml
@model IEnumerable<Ogretmen>
    <h2>Öğretmen listesi</h2>
    <hr>
    <a href="/ogretmen/create" class="btn btn-primary mb-3">Öğretmen Ekle</a>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th style="width: 150px;">@Html.DisplayNameFor(m=>m.OgretmenId)</th>
                <th>@Html.DisplayNameFor(m=>m.Ad)</th>
                <th>@Html.DisplayNameFor(m=>m.Soyad)</th>
                <th>@Html.DisplayNameFor(m=>m.Eposta)</th>
                <th>@Html.DisplayNameFor(m=>m.Telefon)</th>
                <th>@Html.DisplayNameFor(m=>m.BaslamaTarihi)</th>
                <th style="width: 150px;">Action</th>

            </tr>
        </thead>
        <tbody>
            @foreach(var ogretmen in Model)
            {
            <tr>
                <td>@ogretmen.OgretmenId</td>
                <td>@ogretmen.Ad</td>
                <td>@ogretmen.Soyad</td>
                <td>@ogretmen.Eposta</td>
                <td>@ogretmen.Telefon</td>
                <td>@Html.DisplayFor(modelItem=>ogretmen.BaslamaTarihi)</td>
                <td>
                    <a asp-controller="Ogretmen" asp-action="Edit" asp-route-id="@ogretmen.OgretmenId"
                        class="btn btn-sm btn-primary">Edit</a>
                    <a sp-controller="Ogretmen" asp-action="Delete" asp-route-id="@ogretmen.OgretmenId"
                        class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
            }
        </tbody>
    </table>